# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Attach to Trello Card
      uses: delivered/attach-to-trello-card-action@v2.0.0
      with:
        # (public) Trello auth key for account
        trello-key: 3bf529f28f9ad471957887b9478ab465
        # secret Trello auth token for account
        trello-token: 00623aaa303426f5bee8979b847f7a5f41bd768eaacec9bcf3327afc525f8af4
        # should behave like Trello power-up and add (redundant) comment? (`true` to enable)
        add-pr-comment: # optional
        # required if `add-pr-comment` is enabled
        repo-token: # optional, default is 
